language: cpp
before_script:
- echo "deb http://archive.ubuntu.com/ubuntu xenial main universe" | sudo tee -a /etc/apt/sources.list
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -qq g++-5
- sudo apt-get install -qq doxygen
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
script:
- mkdir build
- cd build
- cmake ..
- cmake --build .

- cmake --build . --target package
- cd ..
- doxygen Doxyfile

deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T main-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uruscoder2013:$BINTRAY_API_KEY "https://api.bintray.com/content/grt12112/Homework4/main/$TRAVIS_BUILD_NUMBER/main-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GITHUB_TOKEN 
  keep_history: true
  on:
    branch: master
